package entitiesEnums;

public enum RoomType {
	ONE_PERSON_ROOM_ONE_SINGLE_BED,
	TWO_PERSON_ROOM_ONE_DOUBLE_BED,
	TWO_PERSON_ROOM_TWO_SINGLE_BEDS,
	THREE_PERSON_ROOM_THREE_SINGLE_BEDS,
	THREE_PERSON_ROOM_ONE_DOUBLE_BED_ONE_SINGLE_BED
}
